name: at_mcp
description: A basic MCP (Model Context Protocol) server implementation in Dart.
version: 0.1.0
repository: https://github.com/JeremyTubongbanua/at_mcp

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
