name: at_talk
description: A messaging application using AT Protocol for @xavier and @gary to communicate via stdin/stdout.
version: 0.1.0
repository: https://github.com/JeremyTubongbanua/at_mcp

environment:
  sdk: ^3.8.1

dependencies:
  at_client: ^3.0.77
  at_commons: ^4.0.7
  at_utils: ^3.0.17
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0